export class GeminiService {
  private apiKey: string;
  private baseUrl = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';

  constructor() {
    this.apiKey = process.env.GEMINI_API_KEY || '';
    if (!this.apiKey) {
      throw new Error('GEMINI_API_KEY environment variable is required');
    }
  }

  async generateLlmsContent(storeUrl: string): Promise<string> {
    const prompt = this.buildPrompt(storeUrl);

    const requestBody = {
      contents: [
        {
          parts: [
            {
              text: prompt
            }
          ]
        }
      ],
      tools: [
        {
          "url_context": {}
        }
      ]
    };

    try {
      const response = await fetch(this.baseUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-goog-api-key': this.apiKey
        },
        body: JSON.stringify(requestBody)
      });

      if (!response.ok) {
        throw new Error(`Gemini API error: ${response.status} ${response.statusText}`);
      }

      const data = await response.json();

      if (!data.candidates || data.candidates.length === 0) {
        throw new Error('No content generated by Gemini API');
      }

      const generatedText = data.candidates[0].content.parts[0].text;
      return generatedText.trim();

    } catch (error) {
      console.error('Error calling Gemini API:', error);
      throw error;
    }
  }

  buildPrompt(storeUrl: string): string {
    return `Analyze the website at ${storeUrl} and create a comprehensive llms.txt file.

IMPORTANT: Use the actual website content to create accurate information. Write everything in English.

Follow this structure exactly:

[Brand Name]

[2-3 line brand description explaining what the company does, products/services, and target market]

Language: English
Market/Currency: [Country/Currency from website]
Contact: [Phone, email from website]

Core pages:
Homepage: ${storeUrl}
[Other important pages with full URLs]

Products:
[List 5-10 main products with names and full URLs]

Collections:
[List main product categories/collections with full URLs]

Policies:
Shipping policy: [URL if found]
Refunds/returns: [URL if found]
Privacy: [URL if found]
Terms: [URL if found]

Short answers assistants can reuse:
Q: [Common question about products/services]
A: [Helpful answer with specific details]

Q: [Another common question]
A: [Another helpful answer]

Q: [Third common question]
A: [Third helpful answer]

RULES:
- Use only plain text, no markdown or HTML
- All content must be in English
- Use actual information from the website
- Include full URLs for all links
- Make Q&A practical and helpful
- Do NOT include keywords section
- Focus on being informative and accurate`;
  }
}